<?php
/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace AKKBLFPIM23Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AuthentificationByRefreshTokenRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps refresh_token
     * @var string $refreshToken public property
     */
    public $refreshToken;

    /**
     * @todo Write general description for this property
     * @required
     * @maps grant_type
     * @var string $grantType public property
     */
    public $grantType;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $refreshToken Initialization value for $this->refreshToken
     * @param string $grantType    Initialization value for $this->grantType
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->refreshToken = func_get_arg(0);
            $this->grantType    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['refresh_token'] = $this->refreshToken;
        $json['grant_type']    = $this->grantType;

        return $json;
    }
}
