<?php
/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace AKKBLFPIM23Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AuthentificationByPasswordRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $username public property
     */
    public $username;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $password public property
     */
    public $password;

    /**
     * @todo Write general description for this property
     * @required
     * @maps grant_type
     * @var string $grantType public property
     */
    public $grantType;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $username  Initialization value for $this->username
     * @param string $password  Initialization value for $this->password
     * @param string $grantType Initialization value for $this->grantType
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->username  = func_get_arg(0);
            $this->password  = func_get_arg(1);
            $this->grantType = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['username']   = $this->username;
        $json['password']   = $this->password;
        $json['grant_type'] = $this->grantType;

        return $json;
    }
}
