<?php
/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace AKKBLFPIM23Lib;

use AKKBLFPIM23Lib\Controllers;

/**
 * AKKBLFPIM23Lib client class
 */
class AKKBLFPIM23Client
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthAccessToken = null
    ) {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
    /**
     * Singleton access to Product controller
     * @return Controllers\ProductController The *Singleton* instance
     */
    public function getProduct()
    {
        return Controllers\ProductController::getInstance();
    }
    /**
     * Singleton access to Attribute controller
     * @return Controllers\AttributeController The *Singleton* instance
     */
    public function getAttribute()
    {
        return Controllers\AttributeController::getInstance();
    }
    /**
     * Singleton access to AttributeOption controller
     * @return Controllers\AttributeOptionController The *Singleton* instance
     */
    public function getAttributeOption()
    {
        return Controllers\AttributeOptionController::getInstance();
    }
    /**
     * Singleton access to AttributeGroups controller
     * @return Controllers\AttributeGroupsController The *Singleton* instance
     */
    public function getAttributeGroups()
    {
        return Controllers\AttributeGroupsController::getInstance();
    }
    /**
     * Singleton access to Category controller
     * @return Controllers\CategoryController The *Singleton* instance
     */
    public function getCategory()
    {
        return Controllers\CategoryController::getInstance();
    }
    /**
     * Singleton access to Channel controller
     * @return Controllers\ChannelController The *Singleton* instance
     */
    public function getChannel()
    {
        return Controllers\ChannelController::getInstance();
    }
    /**
     * Singleton access to Currency controller
     * @return Controllers\CurrencyController The *Singleton* instance
     */
    public function getCurrency()
    {
        return Controllers\CurrencyController::getInstance();
    }
    /**
     * Singleton access to Family controller
     * @return Controllers\FamilyController The *Singleton* instance
     */
    public function getFamily()
    {
        return Controllers\FamilyController::getInstance();
    }
    /**
     * Singleton access to FamilyVariant2XOnly controller
     * @return Controllers\FamilyVariant2XOnlyController The *Singleton* instance
     */
    public function getFamilyVariant2XOnly()
    {
        return Controllers\FamilyVariant2XOnlyController::getInstance();
    }
    /**
     * Singleton access to MeasureFamily2XOnly controller
     * @return Controllers\MeasureFamily2XOnlyController The *Singleton* instance
     */
    public function getMeasureFamily2XOnly()
    {
        return Controllers\MeasureFamily2XOnlyController::getInstance();
    }
    /**
     * Singleton access to Misc controller
     * @return Controllers\MiscController The *Singleton* instance
     */
    public function getMisc()
    {
        return Controllers\MiscController::getInstance();
    }
}
