<?php
/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace AKKBLFPIM23Lib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const AKK = "AKK";
}
